quarkus.http.port=8082
quarkus.container-image.build=true
quarkus.container-image.group=nicolasduminil
quarkus.container-image.name=iam-front-end
iam_client/mp-rest/url=http://localhost:8081
fe.quarkus.oidc.auth-server-url=http://localhost:8080/realms/myrealm
#quarkus.oidc.client-id=fe
#quarkus.oidc.credentials.secret=this_is_a_secret
#quarkus.oidc.application-type=web-app
#quarkus.http.auth.permission.authenticated.paths=/*
#quarkus.http.auth.permission.authenticated.policy=authenticated
#quarkus.oidc.token-state-manager.split-tokens=true
fe.quarkus.discovery.endpoint=${quarkus.oidc.auth-server-url}/.well-known/openid-configuration