quarkus.http.port=8082
quarkus.container-image.build=true
quarkus.container-image.group=nicolasduminil
quarkus.container-image.name=iam-front-end
quarkus.jib.jvm-arguments=-agentlib:jdwp=transport=dt_socket\\,server=y\\,suspend=n\\,address=*:5005
iam_client/mp-rest/url=http://localhost:8081
quarkus.keycloak.admin-client.server-url=http://localhost:8080
keycloak.realm=myrealm
quarkus.oidc.auth-server-url=${quarkus.keycloak.admin-client.server-url}/realms/${keycloak.realm}
quarkus.oidc.client-id=fe
quarkus.oidc.application-type=web-app
quarkus.oidc.token-state-manager.split-tokens=true
keycloak.discovery.endpoint=/.well-known/openid-configuration
oauth2.client.id=${quarkus.oidc.client-id}
oauth2.response.type=code
oauth2.scope=openid profile email
oauth2.prompt=login
oauth2.max.age=3600
oauth2.login.hint?=
iam-frontend.sandbox-redirect=keycloak/keycloak-oidc.xhtml
iam-frontend.be-redirect=keycloak/keycloak-oauth20.xhtml
iam-frontend.error-redirect=login-error.xhtml
