version: "3.7"
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    hostname: keycloak
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./scripts/customize.sh:/opt/keycloak/customization/customize.sh
      - ./fe-acc.json:/opt/keycloak/customization/fe-acc.json
      - ./be-client.json:/opt/keycloak/customization/be-client.json
    healthcheck:
      test: [ "CMD", "curl", "--head", "http://localhost:8080/health/ready", "-sf" ]
      interval: 10s
      timeout: 2s
      retries: 15
    command: ["start-dev"]
    network_mode: "host"
  iam-backend:
    image: nicolasduminil/iam-back-end:1.0-SNAPSHOT
    depends_on:
      - keycloak
    container_name: iam-backend
    hostname: iam-backend
    network_mode: "host"
  iam-frontend:
    image: nicolasduminil/iam-front-end:1.0-SNAPSHOT
    depends_on:
      - iam-backend
    container_name: iam-frontend
    hostname: iam-frontend
    network_mode: "host"


