version: "3.7"
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./scripts/customize.sh:/opt/keycloak/customization/customize.sh
    healthcheck:
      test: [ "CMD", "curl", "--head", "http://keycloak:8080/health/ready", "-sf" ]
      interval: 10s
      timeout: 2s
      retries: 5
    command: ["start-dev"]
  iam-backend:
    image: nicolasduminil/iam-back-end:1.0-SNAPSHOT
    depends_on:
      - keycloak
    container_name: iam-backend
    links:
      - keycloak:keycloak
    hostname: iam-backend
    ports:
      - "8081:8081"
  iam-frontend:
    image: nicolasduminil/iam-front-end:1.0-SNAPSHOT
    depends_on:
      - keycloak
      - iam-backend
    container_name: iam-frontend
    links:
      - keycloak:keycloak
    hostname: iam-frontend
    ports:
      - "8082:8082"
