keycloak.tcp-port=8080
keycloak.realm-name=myrealm
keycloak.server-url=http://localhost:${keycloak.tcp_port}
keycloak.issuer-uri=/realm/${keycloak.realm-name}/.well-known/openid-configuration
keycloak.authorization-uri=/auth/realms/${keycloak.realm-name}/protocol/openid-connect/auth