quarkus.http.port=8081
quarkus.container-image.build=true
quarkus.container-image.group=nicolasduminil
quarkus.container-image.name=iam-back-end
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16
quarkus.swagger-ui.always-include=true
keycloak.tcp-port=8080
keycloak.realm-name=myrealm
keycloak.server-url=http://keycloak:${keycloak.tcp-port}
keycloak.issuer-uri=/realms/${keycloak.realm-name}/.well-known/openid-configuration
keycloak.authorization-uri=/auth/realms/${keycloak.realm-name}/protocol/openid-connect/auth
