quarkus.http.port=8081
quarkus.container-image.build=true
quarkus.container-image.group=nicolasduminil
quarkus.container-image.name=iam-back-end
#quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16
quarkus.swagger-ui.always-include=true
keycloak.tcp-port=8080
keycloak.realm-name=myrealm
keycloak.host=keycloak
keycloak.server-url=http://${keycloak.host}:${keycloak.tcp-port}
keycloak.issuer-uri=/realms/${keycloak.realm-name}/.well-known/openid-configuration
keycloak.authorization-uri=/realms/${keycloak.realm-name}/protocol/openid-connect/auth
keycloak.authorization-uri-fmt=${keycloak.authorization-uri}?client_id=%s&response_type=%s&redirect_url=%s
